# Equirectangular model for RICOH THETA S

#==============#
# Camera Model #
#==============#

Camera.name: "LOGITECH C170"
Camera.setup: "monocular"
Camera.model: "perspective"

Camera.fps: 30.0
Camera.cols: 1920
Camera.rows: 960

Camera.color_order: "RGB"

#================#
# ORB Parameters #
#================#

Camera.fx: 608.958435
Camera.fy: 608.723389
Camera.cx: 321.793488
Camera.cy: 240.326843

Camera.k1: 0.0
Camera.k2: 0.0
Camera.p1: 0.0
Camera.p2: 0.0
Camera.k3: 0.0
